/-
This file is generated by `scripts/render_orbita_certificate.py` from
`certificates/parity_hole_v1.json`. Do not edit it by hand.

Canonical envelope SHA-256: 4084331b83ca29898070bbbe39383ae8112011dc733433ef3bc4072b2ab40306
-/
import OrbitaLanguageLimit.Certificate
import OrbitaLanguageLimit.Example

namespace Orbita.LanguageLimit.Generated

open Example

/-- Hash binding to the canonical JSON envelope used to generate this module. -/
def sourceEnvelopeSHA256 : String :=
  "4084331b83ca29898070bbbe39383ae8112011dc733433ef3bc4072b2ab40306"

/-- A concrete proof-carrying exact-hole certificate emitted from the envelope. -/
def parityHoleCertificate : HoleCertificate parityRep firstBit where
  x := (false, false)
  y := (true, true)
  sameRepresentation := rfl
  targetDifferent := by simp [firstBit]

/-- Lean independently checks the certificate's non-representability claim. -/
theorem parityHoleCertificate_sound : ¬ Representable parityRep firstBit :=
  parityHoleCertificate.sound

/-- A concrete one-unit within-fiber separation certificate. -/
def parityGapWitness : GapWitness parityRep firstBitReal 1 where
  x := (false, false)
  y := (true, true)
  sameRepresentation := rfl
  separation := by
    rw [Real.dist_eq]
    norm_num [firstBitReal]

/-- Every representation-only decoder has uniform error at least one half. -/
theorem parityGapWitness_sound
    (g : Set.range parityRep → ℝ)
    {ε : ℝ}
    (hε : UniformErrorBound parityRep firstBitReal g ε) :
    (1 : ℝ) / 2 ≤ ε :=
  parityGapWitness.uniformErrorLowerBound g hε

end Orbita.LanguageLimit.Generated

